spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pet_store
    username: pet_store
    password: pet_store


  jpa:
    hibernate:
      ddl-auto: create      # Drops and recreates all tables every time app starts
    show-sql: true           # Show generated SQL in console
    properties:
      hibernate:
        format_sql: true     # Make SQL output readable
